      SUBROUTINE ADEALLOCATE                                                      
!     THIS SUBROUTINE DEDEALLOCATES ARRAY SIZES                                          
      USE PARM                                                                       
      DEALLOCATE (CPNM,FPSO,FTNM,PSTN,TITOP,TITSO,HEDH,HED)                                                            
	  DEALLOCATE (KW,ICDT,IDN1T,IDN2T,IDNB,IDOT,IDRO,NHY,NQRB,NTX,NISA,&
	  ICUS,IHC,NBE,NBT,IDC,KDC,NTP,KDF,KFL)                                                     
	  DEALLOCATE (ISAL,ISAS,NFED,NHRD,NSAL,NSAO,NSAS)                                                               
	  DEALLOCATE (IIR,KIR,NIR)                                               
	  DEALLOCATE (IAC,IAMF,IAPL,IAUF,IAUI,IAUL,IBSA,IDFH,IDOA,IDR,&
	  IDRL,IDON,IDS,IEXT,IFA,IFD,IFLS,IGO,IGZ,IHDM,ILQF,IMW,IPMP,IPSO,&
	  IPST,IPTS,IRF,IRI,IRO,IRP,IRR,IRRS,ISAO,ISCP)
      DEALLOCATE (ISG,ISPF,IWTH,JBG,JCN,JCN0,JCN1,JD,KC,KP1,KT,KTF,KTMX,&
      KTT,LM,LRD,LUN,LUNS,MXSR,NBCF,NBCT,NBFF,NBFT,NBSA,NBSL,NBW,NDFA,&
      NII,NMW,NPSF,NRO,NVCN,NWDA)
      DEALLOCATE (IPSF,KPSN,JPC,KPC,NPC,IHX) 
	  DEALLOCATE (IHU,IYH,JE,JP,JPL,KGO,NCR,NHU,NYLN)             
	  DEALLOCATE (NCP,NFRT,NPST,NTL)                    
      DEALLOCATE (IDFA,IDFD,IDMU,IGZO,IGZX,IHBS,IYHO,LGIR,NBHS,NCOW,NGZA,&
      NHBS,NYHO)                  
      DEALLOCATE (IDSL,IDSS,IDOW,IHT,KOMP,IFED,NGZ,LID,LORG,IFLO,IHRL,&
      IDFT,IDF0)                          
	  DEALLOCATE (ITL,JH,KDT,LFT,LT,LYR,LPC,LY,IHDT,NGIX,NBSX)                                 
      DEALLOCATE (OSAA,OWSA,PKRZ,RNMN,UK,UN,UP,UW)
      DEALLOCATE (FCST,FK,FN,FNMA,FNMN,FNO,FOC,FP,FPO,FSLT)                                                 
	  DEALLOCATE (PCST,PHLF,PHLS,PKOC,PLCH,PSOL,PWOF,SSPS)                                                 
      DEALLOCATE (COOP,COTL,DKH,DKI,EFM,EMX,FPOP,FRCP,FULU,HE,HMO,ORHI,RHT&            
      ,RIN,RR,STIR,TIL,TLD)                                      
      DEALLOCATE (AEP,ALT,CAF,CKY,CNLV,CNY,CSTS,CPY,DDM,DLAI,DMLA,DMLX,EP,&
      EXTC,FLT,FTO,GMHU,GRDD,GRLV,GSI,HI,HMX,PHUX,PLAX,POPX,PRYF,PRYG,PST,&
      RBMD,RDMX,RLAD,SDW,TBSC,TCPA,TCPY,TOPC,VPD2,VPTH,WA,WAVP,WCY,WSYF,&
      WXYF,XDLAI,XMTU,YLD,YLX)                    
      DEALLOCATE (ABD,AFLG,AGPM,ALGI,ALQ,ARMN,ARMX,ARSD,BA1,BA2,BCOF,BCV,&
      BFFL,BFSN,BFT,BIG,BIR,BR1,BR2,BTC,BTCX,BTCZ,BTK,BTN,BTNX,BTNZ,BTP,&
      BTPX,BTPZ,BV1,BV2,BVIR,CFNP,CHL,CHN,CHS,CHXA,CHXP,CLG,CN0,CN2,CNSX)
      DEALLOCATE (COST,COWW,CPMX,CST1,CV,CVF,CVP,CVRS,CYAV,CYMX,CYSD,&
      DALG,DDLG,DEPC,DHT,DKIN,DKHL,DRT,DST0,DWOC,EFI,EK,EM10,EVRS,EVRT,&
      FBM,FCMN,FCMP,FDSF,FFC,FFPQ,FGC,FGSL,FHP,FIRG,FPF,FPSC,FSFN,FSFP,&
      GMA,GRDL,GWSN,GWST,GWMX,HCLD,HCLN,HLMN,HR0,HSM,OCPD)
      DEALLOCATE (OMAP,ORSD,PAW,PCOF,PDAW,PDPL,PDPL0,PDPLC,PDPLX,PDSKC,&
      PDSW,PEC,PMX,PM10,PRSD,PSTF,PSTM,PSTS,QCAP,QRBQ,QRQB,RCBW,RCF,RCHC,&
      RCHD,RCHK,RCHL,RCHN,RCHS,RCHX,RCSS,RCTW,REPI,RFPK,RFPL,RFPS,RFPW,&
      RFPX,RFTT,RFV,RFV0,RHD,RHTT)
      DEALLOCATE (RINT,RLF,RMXS,ROSP,RRUF,RSAE,RSAP,RSBD,RSDP,RSEE,RSEP,&
      RSF,RSHC,RSK,RSLK,RSOC,RSON,RSOP,RSO3,RSRR,RSSA,RSSP,RST0,RSV,RSVB,&
      RSVE,RSVF,RSVP,RSPK,RSYB,RSYF,RSYN,RSYS,RVE0,RVP0,RZ,RZSW,SALA,SALB,&
      SAMA,SATK,SCI,SCNX,SDVR,SLF,SLT0,SLTX,SMAS,SMEO,SMFN,SMFU,SMKS,SMLA,&
      SMMU,SMNS,SMNU,SMPL,SMPQ,SMPS,SMPY,SMRF,SMSS,SMST,SMTS,SMWS,SMX,&
      SMY1,SMY2,SNO,SOLQ,SPLG,SRAD,SRSD,SSFI,SSIN,SSW)                     
      DEALLOCATE (ST0,STDO,STDOK,STDON,STDOP,STKR,STLT,STP,SW,SWB,SWBD,&
      SWLT,S3,TAGP,TCC,TCS,TFLG,THK,TILG,TKR,TLMF,TMN,TMX,TNOR,TNYL,TOC,&
      TPSF,TRSD,TSLA,TSMY,TSNO,TVGF,TYK,TYN,TYP,U10,UB1,UOB,UPSX,URBF,USL,&
      VAC,VALF1,VAP,VCHA,VCHB,VFPA,VFPB,VIMX,VIRT,VLG,VLGB,VLGI,VLGM,VLGN,&
      VPU,VRSE,VSK,VSLT,WDRM)                                                     
      DEALLOCATE (WK,WS,WSA,WSX,WTMB,WTBL,WTMN,WTMU,WTMX,XCT,XHSM,XIDK,XIDS,&
      XMAP,XNS,XRFI,YCT,YLC,YLS,YTN,YTX,ZBMC,ZBMN,ZCO,ZCOB,ZEK,ZFK,ZFOP,&
      ZHPC,ZHPN,ZHSC,ZHSN,ZLM,ZLMC,ZLMN,ZLS,ZLSC,ZLSL,ZLSLC,ZLSLNC,ZLSN,&
      ZNMA,ZNMN,ZNMU,ZNOA,ZNOS,ZNOU,ZOC,ZON,ZPMA,ZPML,ZPMS,ZPMU,ZPO,ZPOU,&
      ZSK,ZSLT,ZTP)                                               
      DEALLOCATE (CPVH,DPMT,DRAV,ERAV,HYDV,RCTC,PRAV,PRB,PSZM,QC,QDR,&
      QDRN,QDRP,QN,QP,QPR,QPU,QRF,QRFN,QRFP,QRP,QURB,QVOL,RQRB,RSFN,&
      RSSF,RWSA,SHYD,SMIO,SQVL,SST,STY,TC,TCAV,TCMN,TCMX,TSFK,TSFN,WYLD,&
      YC,YCOU,YCWN,YMNU,YN,YNOU,YNWN,YP,YPOU,YPWN,YW)
      DEALLOCATE (PSO3,PSON,PSOP,PSOQ,PSOY,PQPS,PSSP,PYPS)
      DEALLOCATE (QGA,RFDT,VARW)
      DEALLOCATE (EO5,RF5,SCFS,XMS,ASW,CX,QIN,SET,SRD,SRMX,TAMX,TCN,TCVF,&
      TEI,TET,THRL,TQ,TR,TRHT,TSN,TSR,TSY,TXMX,TXMN,TQN,TQP,TQPU,TYON,&
      TYTP,TYW,CNSC)
      DEALLOCATE (ALS,BD,BDD,BDM,BDP,BPT,CAC,CBN,CEC,CLA,CNDS,CNRT,CPRH,&
      CPRV,DHN,ECND,EQKE,EQKS,EXCK,FE26,FIXK,FOP,HCL,PH,PO,PSP,ROK,RSD,&
      RSDM,SAN,SATC,SEV,SIL,SMB,SOLK,SULF)
      DEALLOCATE (SWST,STFR,STMP,VNO3,WBMN,WCMU,WCOU,WHPC,WHPN,WHSC,&
      WHSN,WKMU,WLM,WLMC,WLMN,WLS,WLSC,WLSL,WLSLC,WLSLNC,WLSN,&
      WNMU,WNOU,WOC,WON,WPMA,WPML,WPMS,WPMU,WPO,WPOU,WSLT,WT,Z)
      DEALLOCATE (ACET,AJHI,AWC,CAW,CPHT,CSTF,DM,DMF,DM1,ETG,FRTK,FRTN,&
      FRTP,HU,HUF,HUI,PPL0,RD,RDF,REG,RW,SLAI,SLA0,SRA,STD,STDK,STDL,STDN)               
      DEALLOCATE (STDP,STL,SWH,SWP,TCAW,TDM,TETG,TFTK,TFTN,TFTP,THU,TRA,&
      TRD,TVIR,TYL1,TYL2,TYLK,TYLN,TYLP,UK1,UNA,UN1,UP1,VIR,WCHT,WLV,&
      XLAI,XDLA0,YLD1,YLD2,YLKF,YLNF,YLPF)
      DEALLOCATE(ACO2C,AFP,AN2OC,AO2C,CGCO2,CGN2O,CGO2,CLCO2,CLN2O,CLO2)
      DEALLOCATE(DCO2GEN,DN2G,DN2OG,DO2CONS,DPRC,DPRN,DPRO,DRWX,EAR,FC,&
      HKPC,HKPN)
      DEALLOCATE(HKPO,RSPC,RWTZ,S15,SMEA,SMES,SOT,SSFCO2,SSFN2O,SSFO2)
      DEALLOCATE(TPOR,VCO2,VN2O,VO2,VFC,VWC,VWP,WBMC,WCO2G,WCO2L,WN2O,&
      WN2OG,WN2OL,WNO2,WNH3,WNO3,WO2G,WO2L,XN2O,ZC)    
      DEALLOCATE (YHY,SMH,SMYH,VARH,QPST,RSPS,TSPS,YPST,SRCH,CPFH,QSF,&
      SSF,SM,SMY,VAR,CTSA,VQ,VY,GWPS,PFOL,ANA,FNMX,GCOW,GZLM,DUMP,FFED,&
      GZRT,VURN,PPX,YSD,PCT,PCTH,SQB,SYB,FNP,SMYRP,BK,BN,BP,BLG,BWN,DLAP,&
      FRST,PPCF,PPLP,RWPC,STX,WAC2)    
      DEALLOCATE (SMMH,PVQ,PVY,PSTE,PSTR,PSSF,PSTZ,CND,SMM,STV,SMS,SOL,&
      FIRX,QIR,RSTK,TIR,VIRR,WFA,PHU,POP,PPLA,VARC,SMAP,SMYP,VARP,&
      SMMRP,SMRP)
      !SPQ(5,20,MHY),SPQC(5,20,MHY),SPY(5,20,MHY)
      DEALLOCATE (TSFC,SOIL,HUSC,RWT,STDA,SFCP,SFMO,XZP,QHY)
      DEALLOCATE (SMMP,SMMC)
!     DEALLOCATE (APQ(5,20,100,MHY),APQC(5,20,100,MHY),APY(5,20,100,MHY)&              
!    &,AQB(5,20,100,MHY),AYB(5,20,100,MHY),SMMP(20,MPS,12,MSA),SMMC(15,&             
!    &MNC,12,MSA))                                                                                            
      RETURN                                                                         
      END                                                                            
                                                                                     
