      SUBROUTINE HSWBL(P,WYI,WYO,ETSA,EVRS,DPK,RG,RGDL,QWT,RBK,BSNO,&
      FSNO,BSW,FSW,BRSV,FRSV,BGWS,FGWS,FSWL,ISA,KFL,KW,NBSA,MSO)
!     APEX1501
!     THIS SUBPROGRAM CHECKS THE SUBAREA SOIL WATER BALANCE AT THE END
!     OF A SIMULATION.
      DIMENSION NBSA(ISA),KW(MSO),KFL(MSO+1)
      DF=BSW+BSNO+BRSV+BGWS+P+WYI-WYO-ETSA-EVRS-DPK+RG-RGDL+QWT+RBK&
      -FSW-FSNO-FRSV-FGWS-FSWL 
      PER=200.*DF/(BSNO+FSNO+BSW+FSW+BRSV+FRSV+BGWS+FGWS)
	  IF(ABS(PER)>1..OR.KFL(1)>0)THEN
	      WRITE(KW(1),2)ISA,NBSA(ISA) 
          WRITE(KW(1),3)PER,DF,BSW,BSNO,BRSV,BGWS,P,WYI,WYO,ETSA,EVRS,DPK,&
          RG,RGDL,QWT,RBK,FSW,FSNO,FRSV,FGWS,FSWL
	  END IF
      RETURN
    2 FORMAT(/T10,'SOIL WATER BALANCE',2X,'SA#= ',I8,1X,'ID= ',I8)
    3 FORMAT(5X,'PER =',E13.6,2X,'DF  =',E13.6,2X,'BSW =',E13.6,2X,'BSNO=',&
      E13.6,2X,'BRSV=',E13.6,2X,'BGWS=',E13.6/5X,'PCP =',E13.6,2X,'WYLI=',&
      E13.6,2X,'WYLO=',E13.6,2X,'ETSA=',E13.6,2X,'EVRS=',E13.6,2X,'DPRK=',&
      E13.6/5X,'IRG =',E13.6,2X,'IREF=',E13.6,2X,'QIN =',E13.6,2X,'RBK =',&
      E13.6,2X,'FSW =',E13.6,2X,'FSNO=',E13.6/5X,'FRSV=',E13.6,2X,'FGWS=',&
      E13.6,2X,'FSWL=',E13.6)
      END