      SUBROUTINE HSWBLD(P,QSA,WYI,WYO,ETSA,EVRS,PKRZ,DPK,RSSF,RG,XEF,&
      QWT,RBK,BSNO,FSNO,BSW,FSW,BRSV,FRSV,BGWS,FGWS,BSALA,FSALA,ISA,NBSA,&
      IY,MO,KDA,KW,MSO)
!     APEX1501
!     THIS SUBPROGRAM CHECKS THE SOIL WATER BALANCE AT THE END OF A
!     SIMULATION.
      DIMENSION NBSA(ISA),KW(MSO)
      DATA AD1/0./
      DF=BSW+BSNO+BRSV+BGWS+P+WYI-WYO-ETSA-EVRS-DPK+RG-XEF+QWT+RBK&
      -FSW-FSNO-FRSV-FGWS
      AD1=AD1+DF
	  IF(ABS(DF)>.001)THEN
	      WRITE(KW(1),2)ISA,NBSA(ISA),IY,MO,KDA
          WRITE(KW(1),3)DF,BSW,BSNO,BRSV,BGWS,P,QSA,WYI,WYO,ETSA,EVRS,&
          PKRZ,DPK,RSSF,RG,XEF,QWT,RBK,FSW,FSNO,FRSV,FGWS,BSALA,FSALA,AD1
      END IF
      RETURN
    2 FORMAT(/T10,'SOIL WATER BALANCE',2X,'SA#= ',I8,1X,'ID= ',I8,2X,3I4)
    3 FORMAT(5X,'DF  =',E13.6,2X,'BSW =',E13.6,2X,'BSNO=',E13.6,2X,'BRSV=',&
      E13.6,2X,'BGWS=',E13.6,2X,'PCP =',E13.6/5X,'QSA =',E13.6,2X,'WYLI=',&
      E13.6,2X,'WYLO=',E13.6,2X,'ETSA=',E13.6,2X,'EVRS=',E13.6,2X,'PKRZ=',&
      E13.6/5X,'DPRK=',E13.6,2X,'RSSF=',E13.6,2X,'IRG =',E13.6,2X,'IREF=',&
      E13.6,2X,'QIN =',E13.6,2X,'RBK =',E13.6/5X,'FSW =',E13.6,2X,'FSNO=',&
      E13.6,2X,'FRSV=',E13.6,2X,'FGWS=',E13.6,2X,'BSAL=',E13.6,2X,'FSAL=',&
      E13.6/5X,'ERSM=',E13.6)
      END