      MODULE HISAFE

      TYPE , BIND(C) ::Hisafe_

      INTEGER::HI_IBD
      INTEGER::HI_IBDT
      INTEGER::HI_ICDP
      INTEGER::HI_ICMD
      INTEGER::HI_ICO2
      INTEGER::HI_ICP
      INTEGER::HI_IDA
      INTEGER::HI_IDAY
      INTEGER::HI_IDIR
      INTEGER::HI_IDN1
      INTEGER::HI_IDN2
      INTEGER::HI_IDNT
      INTEGER::HI_IDO
      INTEGER::HI_IERT
      INTEGER::HI_IET
      INTEGER::HI_IGC
      INTEGER::HI_IGN
      INTEGER::HI_IGSD
      INTEGER::HI_IHD
      INTEGER::HI_IHRD
      INTEGER::HI_IHV
      INTEGER::HI_IHUS
      INTEGER::HI_IHY
      INTEGER::HI_III
      INTEGER::HI_IKAT
      INTEGER::HI_IMON
      INTEGER::HI_INFL
      INTEGER::HI_INP
      INTEGER::HI_IOF
      INTEGER::HI_IOW
      INTEGER::HI_IOX
      INTEGER::HI_IPAT
      INTEGER::HI_IPC
      INTEGER::HI_IPD
      INTEGER::HI_IPF
      INTEGER::HI_IPL
      INTEGER::HI_IPRK
      INTEGER::HI_IPY
      INTEGER::HI_IPYI
      INTEGER::HI_IRGX
      INTEGER::HI_IRH
      INTEGER::HI_IRUN
      INTEGER::HI_ISA
      INTEGER::HI_ISAP
      INTEGER::HI_ISCN
      INTEGER::HI_ISLF
      INTEGER::HI_ISL
      INTEGER::HI_ISTA
      INTEGER::HI_ISW
      INTEGER::HI_IT1
      INTEGER::HI_IT2
      INTEGER::HI_IT3
      INTEGER::HI_ITYP
      INTEGER::HI_IUN
      INTEGER::HI_IWI
      INTEGER::HI_IWTB
      INTEGER::HI_IY
      INTEGER::HI_IYER
      INTEGER::HI_IYR
      INTEGER::HI_IYR0
      INTEGER::HI_IYX
      INTEGER::HI_JD0
      INTEGER::HI_JDA
      INTEGER::HI_JDE
      INTEGER::HI_JDHU
      INTEGER::HI_JJK
      INTEGER::HI_JT1
      INTEGER::HI_JT2
      INTEGER::HI_KDA
      INTEGER::HI_KF
      INTEGER::HI_KI
      INTEGER::HI_KP
      INTEGER::HI_LBP
      INTEGER::HI_KND
      INTEGER::HI_LC
      INTEGER::HI_LGRZ
      INTEGER::HI_LGZ
      INTEGER::HI_LND
      INTEGER::HI_LNS
      INTEGER::HI_LPD
      INTEGER::HI_LPYR
      INTEGER::HI_LW
      INTEGER::HI_MASP
      INTEGER::HI_MBS
      INTEGER::HI_MCA12
      INTEGER::HI_MFT
      INTEGER::HI_MHD
      INTEGER::HI_MHP
      INTEGER::HI_MHX
      INTEGER::HI_MHY
      INTEGER::HI_ML1
      INTEGER::HI_MNC
      INTEGER::HI_MNT
      INTEGER::HI_MNUL
      INTEGER::HI_MO
      INTEGER::HI_MO1
      INTEGER::HI_MOW
      INTEGER::HI_MPO
      INTEGER::HI_MPS
      INTEGER::HI_MRO
      INTEGER::HI_MSA
      INTEGER::HI_MSC
      INTEGER::HI_MSCP
      INTEGER::HI_MSL
      INTEGER::HI_MXT
      INTEGER::HI_MXW
      INTEGER::HI_NAQ
      INTEGER::HI_NBCL
      INTEGER::HI_NBCX
      INTEGER::HI_NBDT
      INTEGER::HI_NBFX
      INTEGER::HI_NBMX
      INTEGER::HI_NBON
      INTEGER::HI_NBYR
      INTEGER::HI_NCMD
      INTEGER::HI_NCMO
      INTEGER::HI_ND
      INTEGER::HI_NDF
      INTEGER::HI_NDP
      INTEGER::HI_NDRV
      INTEGER::HI_NDT
      INTEGER::HI_NDVSS
      INTEGER::HI_NDWT
      INTEGER::HI_NEV
      INTEGER::HI_NGN
      INTEGER::HI_NGN0
      INTEGER::HI_NJC
      INTEGER::HI_NKA
      INTEGER::HI_NKD
      INTEGER::HI_NKS
      INTEGER::HI_NKY
      INTEGER::HI_NOFL
      INTEGER::HI_NOP
      INTEGER::HI_NPD
      INTEGER::HI_NPRC
      INTEGER::HI_NPSO
      INTEGER::HI_NRF
      INTEGER::HI_NSH
      INTEGER::HI_NSM
      INTEGER::HI_MSO
      INTEGER::HI_NSNN
      INTEGER::HI_NSTP
      INTEGER::HI_NSX
      INTEGER::HI_NSZ
      INTEGER::HI_NYD
      INTEGER::HI_NT0
      INTEGER::HI_NT1
      INTEGER::HI_NTV
      INTEGER::HI_NUPC
      INTEGER::HI_NWP
      INTEGER::HI_NWTH
      INTEGER::HI_KDT1(800)
      INTEGER::HI_KDC1(1500)
      INTEGER::HI_KDF1(1200)
      INTEGER::HI_KDP1(1000)
      INTEGER::HI_KA(100)
      INTEGER::HI_NXP(90)
      INTEGER::HI_KR(60)
      INTEGER::HI_KDT2(50)
      INTEGER::HI_KD(40)
      INTEGER::HI_KY(40)
      INTEGER::HI_KDP(50)
      INTEGER::HI_NHC(26)
      INTEGER::HI_KS(20)
      INTEGER::HI_NWDR(16)
      INTEGER::HI_IX(13)
      INTEGER::HI_NC(13)
      INTEGER::HI_IDG(12)
      INTEGER::HI_IX0(12)
      INTEGER::HI_IAD(10)
      INTEGER::HI_ICMO(10)
      INTEGER::HI_NWPD(10)
      INTEGER::HI_NDC(11)
      INTEGER::HI_JX(7)
      INTEGER::HI_KGN(5)
      INTEGER::HI_JC(4)

      !!!INTEGER ALLOCATE REPLACED BY MAX FIXED SIZE
      INTEGER::HI_IAC(1)
      INTEGER::HI_IAMF(1)
      INTEGER::HI_IAPL(1)
      INTEGER::HI_IAUF(1)
      INTEGER::HI_IAUI(1)
      INTEGER::HI_IAUL(1)
      INTEGER::HI_IBSA(1)
      INTEGER::HI_ICDT(4)
      INTEGER::HI_ICUS(300)
      INTEGER::HI_IDC(200)
      INTEGER::HI_IDF0(6,1)
      INTEGER::HI_IDFA(10,1)
      INTEGER::HI_IDFD(10,1)
      INTEGER::HI_IDFH(1)
      INTEGER::HI_IDFT(6,1)
      INTEGER::HI_IDMU(10,1)
      INTEGER::HI_IDN1T(4)
      INTEGER::HI_IDN2T(4)
      INTEGER::HI_IDNB(4)
      INTEGER::HI_IDNF(1)
      INTEGER::HI_IDOA(1)
      INTEGER::HI_IDON(1)
      INTEGER::HI_IDOT(4)
      INTEGER::HI_IDOW(1,1)
      INTEGER::HI_IDR(1)
      INTEGER::HI_IDRL(1)
      INTEGER::HI_IDRO(4)
      INTEGER::HI_IDS(1)
      INTEGER::HI_IDSL(1,1)
      INTEGER::HI_IDSS(1,1)
      INTEGER::HI_IEXT(1)
      INTEGER::HI_IFA(1)
      INTEGER::HI_IFD(1)
      INTEGER::HI_IFED(10,1)
      INTEGER::HI_IFLO(12,1)
      INTEGER::HI_IFLS(1)
      INTEGER::HI_IGO(1)
      INTEGER::HI_IGZ(1)
      INTEGER::HI_IGZO(10,1)
      INTEGER::HI_IGZX(10,1)
      INTEGER::HI_IHBS(10,1)
      INTEGER::HI_IHC(300)
      INTEGER::HI_IHDM(1)
      INTEGER::HI_IHDT(4,10,1)
      INTEGER::HI_IHRL(12,1)
      INTEGER::HI_IHT(300,1)
      INTEGER::HI_IHU(200,1)
      INTEGER::HI_IHX(3)
      INTEGER::HI_IIR(45)
      INTEGER::HI_ILQF(1)
      INTEGER::HI_IMW(1)
      INTEGER::HI_IPMP(1)
      INTEGER::HI_IPSF(5)
      INTEGER::HI_IPSO(1)
      INTEGER::HI_IPST(1)
      INTEGER::HI_IPTS(1)
      INTEGER::HI_IRF(1)
      INTEGER::HI_IRI(1)
      INTEGER::HI_IRO(1)
      INTEGER::HI_IRP(1)
      INTEGER::HI_IRR(1)
      INTEGER::HI_IRRS(1)
      INTEGER::HI_ISAL(1)
      INTEGER::HI_ISAO(1)
      INTEGER::HI_ISAS(1)
      INTEGER::HI_ISCP(1)
      INTEGER::HI_ISG(1)
      INTEGER::HI_ISPF(1)
      INTEGER::HI_ITL(45,300,1)
      INTEGER::HI_IWTH(1)
      INTEGER::HI_IYH(200,1)
      INTEGER::HI_IYHO(10,1)
      INTEGER::HI_JBG(1)
      INTEGER::HI_JCN(1)
      INTEGER::HI_JCN0(1)
      INTEGER::HI_JCN1(1)
      INTEGER::HI_JD(1)
      INTEGER::HI_JE(200,1)
      INTEGER::HI_JH(45,300,1)
      INTEGER::HI_JP(200,1)
      INTEGER::HI_JPC(60)
      INTEGER::HI_JPL(200,1)
      INTEGER::HI_KC(1)
      INTEGER::HI_KDC(200)
      INTEGER::HI_KDF(60)
      INTEGER::HI_KDT(12,200,1)
      INTEGER::HI_KFL(50)
      INTEGER::HI_KGO(200,1)
      INTEGER::HI_KIR(45)
      INTEGER::HI_KOMP(300,1)
      INTEGER::HI_KP1(1)
      INTEGER::HI_KPC(60)
      INTEGER::HI_KPSN(5)
      INTEGER::HI_KT(1)
      INTEGER::HI_KTF(1)
      INTEGER::HI_KTMX(1)
      INTEGER::HI_KTT(1)
      INTEGER::HI_KW(51)
      INTEGER::HI_LFT(45,300,1)
      INTEGER::HI_LGIR(10,1)
      INTEGER::HI_LID(13,1)
      INTEGER::HI_LM(1)
      INTEGER::HI_LORG(12,1)
      INTEGER::HI_LPC(45,60,1)
      INTEGER::HI_LRD(1)
      INTEGER::HI_LT(45,300,1)
      INTEGER::HI_LUN(1)
      INTEGER::HI_LUNS(1)
      INTEGER::HI_LY(45,200,1)
      INTEGER::HI_LYR(45,300,1)
      INTEGER::HI_MXSR(1)
      INTEGER::HI_NBCF(1)
      INTEGER::HI_NBCT(1)
      INTEGER::HI_NBE(300)
      INTEGER::HI_NBFF(1)
      INTEGER::HI_NBFT(1)
      INTEGER::HI_NBHS(10,1)
      INTEGER::HI_NBSA(1)
      INTEGER::HI_NBSL(1)
      INTEGER::HI_NBSX(4,10,1)
      INTEGER::HI_NBT(300)
      INTEGER::HI_NBW(1)
      INTEGER::HI_NCOW(10,1)
      INTEGER::HI_NCP(45,1)
      INTEGER::HI_NCR(200,1)
      INTEGER::HI_NDFA(1)
      INTEGER::HI_NFED(1)
      INTEGER::HI_NFRT(45,1)
      INTEGER::HI_NGIX(1,10,1)
      INTEGER::HI_NGZ(10,1)
      INTEGER::HI_NGZA(10,1)
      INTEGER::HI_NHBS(10,1)
      INTEGER::HI_NHRD(1)
      INTEGER::HI_NHU(200,1)
      INTEGER::HI_NHY(4)
      INTEGER::HI_NII(1)
      INTEGER::HI_NIR(45)
      INTEGER::HI_NISA(4)
      INTEGER::HI_NMW(1)
      INTEGER::HI_NPC(60)
      INTEGER::HI_NPSF(1)
      INTEGER::HI_NPST(45,1)
      INTEGER::HI_NQRB(4)
      INTEGER::HI_NRO(1)
      INTEGER::HI_NSAL(1)
      INTEGER::HI_NSAO(1)
      INTEGER::HI_NSAS(1)
      INTEGER::HI_NTL(45,1)
      INTEGER::HI_NTP(200)
      INTEGER::HI_NTX(4)
      INTEGER::HI_NVCN(1)
      INTEGER::HI_NWDA(1)
      INTEGER::HI_NYHO(10,1)
      INTEGER::HI_NYLN(200,1)

        REAL::HI_ACW
        REAL::HI_ADEO
        REAL::HI_ADHY
        REAL::HI_ADRF
        REAL::HI_AEPT
        REAL::HI_AET
        REAL::HI_AFN
        REAL::HI_AGP
        REAL::HI_AHSM
        REAL::HI_AJWA
        REAL::HI_ALG
        REAL::HI_ALMN
        REAL::HI_ALTC
        REAL::HI_AL5
        REAL::HI_AMPX
        REAL::HI_ANG
        REAL::HI_AMSR
        REAL::HI_AVT
        REAL::HI_BETA
        REAL::HI_BRNG
        REAL::HI_BS1
        REAL::HI_BS2
        REAL::HI_BXCT
        REAL::HI_BYCT
        REAL::HI_CBVT
        REAL::HI_CLF
        REAL::HI_CLT
        REAL::HI_CMM
        REAL::HI_CMS
        REAL::HI_CN
        REAL::HI_CNO3I
        REAL::HI_COIR
        REAL::HI_COL
        REAL::HI_CON
        REAL::HI_COP
        REAL::HI_CO2
        REAL::HI_COS1
        REAL::HI_CPH0
        REAL::HI_CPV0
        REAL::HI_CPVV
        REAL::HI_CQNI
        REAL::HI_CRLNC
        REAL::HI_CRUNC
        REAL::HI_CSFX
        REAL::HI_CSLT
        REAL::HI_D150
        REAL::HI_DAYL
        REAL::HI_DD
        REAL::HI_DEMR
        REAL::HI_DMN   !! Inserted MB 7/19/19
        REAL::HI_DN2O
        REAL::HI_DRSW
        REAL::HI_DRTO
        REAL::HI_DTG
        REAL::HI_DTHY
        REAL::HI_DUR
        REAL::HI_DURG
        REAL::HI_DVOL
        REAL::HI_DZ10
        REAL::HI_DZDN
        REAL::HI_EI
        REAL::HI_ELEV
        REAL::HI_EO
        REAL::HI_ERTN
        REAL::HI_ERTO
        REAL::HI_ERTP
        REAL::HI_ES
        REAL::HI_EXNN
        REAL::HI_EXPK
        REAL::HI_FL
        REAL::HI_FULP
        REAL::HI_FW
        REAL::HI_GWBX
        REAL::HI_GX
        REAL::HI_HGX
        REAL::HI_HMN
        REAL::HI_HRLT
        REAL::HI_HR1
        REAL::HI_PB
        REAL::HI_PI2
        REAL::HI_PIT
        REAL::HI_PMOEO
        REAL::HI_PMORF
        REAL::HI_PRFF
        REAL::HI_PSTX
        REAL::HI_QAPY
        REAL::HI_QRB
        REAL::HI_QSFN
        REAL::HI_QSFP
        REAL::HI_QTH
        REAL::HI_RAMX
        REAL::HI_REP
        REAL::HI_RFNC
        REAL::HI_RFQN
        REAL::HI_RFRA
        REAL::HI_RGIN
        REAL::HI_RGRF
        REAL::HI_RHCF
        REAL::HI_RHM
        REAL::HI_RHP
        REAL::HI_RHS
        REAL::HI_RM
        REAL::HI_RMNR
        REAL::HI_RMX0
        REAL::HI_RNO3
        REAL::HI_RRF
        REAL::HI_RTP
        REAL::HI_RUNT
        REAL::HI_RWO
        REAL::HI_SAET
        REAL::HI_SALF
        REAL::HI_SAT
        REAL::HI_SBAL
        REAL::HI_SCN
        REAL::HI_SCN2
        REAL::HI_SDEG
        REAL::HI_SDEP
        REAL::HI_SDN
        REAL::HI_SDRF
        REAL::HI_SEP
        REAL::HI_SGMN
        REAL::HI_SHRL
        REAL::HI_SK
        REAL::HI_SML
        REAL::HI_SMNR
        REAL::HI_SMP
        REAL::HI_SMSQ
        REAL::HI_SN2
        REAL::HI_SN2O
        REAL::HI_SNIT
        REAL::HI_SN
        REAL::HI_SNMN
        REAL::HI_SNOF
        REAL::HI_SNPKT
        REAL::HI_SOFU
        REAL::HI_SP
        REAL::HI_SPRC
        REAL::HI_SPRF
        REAL::HI_SRPM
        REAL::HI_SSFK
        REAL::HI_SSFN
        REAL::HI_SSST
        REAL::HI_STND
        REAL::HI_SUK
        REAL::HI_SUN
        REAL::HI_SUP
        REAL::HI_SVOL
        REAL::HI_SX
        REAL::HI_SYMU
        REAL::HI_SYW
        REAL::HI_TA
        REAL::HI_TCF      !!Inserted MB 7/29/19
        REAL::HI_TCL      !!Inserted MB 7/29/19
        REAL::HI_TCR      !!Inserted MB 7/29/19
        REAL::HI_TDEG
        REAL::HI_TDEP
        REAL::HI_TEVP
        REAL::HI_TEV1
        REAL::HI_TFMA
        REAL::HI_TFMN
        REAL::HI_TFNO
        REAL::HI_THW
        REAL::HI_TLA
        REAL::HI_TLF      !!Inserted MB 7/29/19
        REAL::HI_TMAF
        REAL::HI_TMAP
        REAL::HI_TMPD
        REAL::HI_TNC      !!Inserted MB 7/29/19
        REAL::HI_TNF      !!Inserted MB 7/29/19
        REAL::HI_TPRK
        REAL::HI_TPSP
        REAL::HI_TREV
        REAL::HI_TRFR
        REAL::HI_TRSP
        REAL::HI_TSAE
        REAL::HI_TSFS
        REAL::HI_TX
        REAL::HI_TXXM
        REAL::HI_UK2
        REAL::HI_UKM
        REAL::HI_UNM      !!Inserted MB 8/13/19
        REAL::HI_UNR
        REAL::HI_UN2
        REAL::HI_UPM
        REAL::HI_UPR
        REAL::HI_UP2
        REAL::HI_USTRT
        REAL::HI_USTT
        REAL::HI_USTW
        REAL::HI_UX
        REAL::HI_UXP
        REAL::HI_V56
        REAL::HI_V57
        REAL::HI_VGF
        REAL::HI_VMU
        REAL::HI_VPD
        REAL::HI_V1
        REAL::HI_V3
        REAL::HI_WAGE
        REAL::HI_WB
        REAL::HI_WCF
        REAL::HI_WCYD
        REAL::HI_WDN
        REAL::HI_WFX
        REAL::HI_WIM
        REAL::HI_WIP
        REAL::HI_WKA
        REAL::HI_WKMNH3
        REAL::HI_WKMNO2
        REAL::HI_WKMNO3
        REAL::HI_WMP
        REAL::HI_WNCMAX
        REAL::HI_WNCMIN
        REAL::HI_WTN
        REAL::HI_XCS
        REAL::HI_XDA
        REAL::HI_XDA1
        REAL::HI_XET
        REAL::HI_XK1
        REAL::HI_XK2
        REAL::HI_XKN1
        REAL::HI_XKN3
        REAL::HI_XKN5
        REAL::HI_XKP1
        REAL::HI_XKP2
        REAL::HI_XSA
        REAL::HI_XSL
        REAL::HI_YCS
        REAL::HI_YERO
        REAL::HI_YEW
        REAL::HI_YEWN
        REAL::HI_YLAT
        REAL::HI_YLAZ
        REAL::HI_YLN
        REAL::HI_YLP
        REAL::HI_YMP
        REAL::HI_YSL
        REAL::HI_YWKS
        REAL::HI_ZF
        REAL::HI_ZQT
        REAL::HI_XTP(100)
        REAL::HI_XYP(100)
        REAL::HI_PRMT(110)
        REAL::HI_SMYR(21)
        REAL::HI_VARS(20)
        REAL::HI_RNCF(12)
        REAL::HI_TAV(12)
        REAL::HI_TMNF(12)
        REAL::HI_TMXF(12)
        REAL::HI_UAV0(12)
        REAL::HI_UAVM(12)
        REAL::HI_AWXP(10)
        REAL::HI_RFSG(10)
        REAL::HI_SMSO(9)
        REAL::HI_OPV(7)
        REAL::HI_SMSW(6)
        REAL::HI_PSZ(5)
        REAL::HI_PSZX(5)
        REAL::HI_PSZY(5)
        REAL::HI_BUS(4)
        REAL::HI_WX(3)
        REAL::HI_XAV(3)
        REAL::HI_XDV(3)
        REAL::HI_XIM(3)
        REAL::HI_XRG(3)


      REAL::HI_SMMR(21,12)
      REAL::HI_SMR(21,12)
      REAL::HI_DIR(12,16)
      REAL::HI_OBMN(10,12)
      REAL::HI_OBMNX(10,12)
      REAL::HI_OBMX(10,12)
      REAL::HI_OBSL(10,12)
      REAL::HI_PCF(10,12)
      REAL::HI_RH(10,12)
      REAL::HI_SDTMN(10,12)
      REAL::HI_SDTMX(10,12)
      REAL::HI_WFT(10,12)
      REAL::HI_WI(10,12)
      REAL::HI_SCRP(30,2)
      REAL::HI_CQRB(8,17,4)
      REAL::HI_RST(3,10,12)
      REAL::HI_PRW(2,10,12)

!!!REAL ALLOCATE REPLACED BY MAX FIXED SIZE
      REAL::HI_ABD(1)
      REAL::HI_ACET(200,1)
      REAL::HI_ACO2C(31,1)
      REAL::HI_AEP(200)
      REAL::HI_AFLG(1)
      REAL::HI_AFP(31,1)
      REAL::HI_AGPM(1)
      REAL::HI_AJHI(200,1)
      REAL::HI_ALGI(1)
      REAL::HI_ALQ(1)
      REAL::HI_ALS(12,1)
      REAL::HI_ALT(200)
      REAL::HI_AN2OC(31,1)
      REAL::HI_ANA(45,1)
      REAL::HI_AO2C(31,1)
      REAL::HI_ARMN(1)
      REAL::HI_ARMX(1)
      REAL::HI_ARSD(1)
      REAL::HI_ASW(12,1)
      REAL::HI_AWC(200,1)
      REAL::HI_BA1(1)
      REAL::HI_BA2(1)
      REAL::HI_BCOF(1)
      REAL::HI_BCV(1)
      REAL::HI_BD(12,1)
      REAL::HI_BDD(12,1)
      REAL::HI_BDM(12,1)
      REAL::HI_BDP(12,1)
      REAL::HI_BFFL(1)
      REAL::HI_BFSN(1)
      REAL::HI_BFT(1)
      REAL::HI_BGWS(1)
      REAL::HI_BIG(1)
      REAL::HI_BIR(1)
      REAL::HI_BK(4,200)
      REAL::HI_BLG(3,200)
      REAL::HI_BN(4,200)
      REAL::HI_BP(4,200)
      REAL::HI_BPT(12,1)
      REAL::HI_BR1(1)
      REAL::HI_BR2(1)
      REAL::HI_BRSV(1)
      REAL::HI_BSALA(1)
      REAL::HI_BSNO(1)
      REAL::HI_BTC(1)
      REAL::HI_BTCX(1)
      REAL::HI_BTCZ(1)
      REAL::HI_BTK(1)
      REAL::HI_BTN(1)
      REAL::HI_BTNX(1)
      REAL::HI_BTNZ(1)
      REAL::HI_BTP(1)
      REAL::HI_BTPX(1)
      REAL::HI_BTPZ(1)
      REAL::HI_BV1(1)
      REAL::HI_BV2(1)
      REAL::HI_BVIR(1)
      REAL::HI_BWN(3,200)
      REAL::HI_CAC(12,1)
      REAL::HI_CAF(200)
      REAL::HI_CAW(200,1)
      REAL::HI_CBN(12,1)
      REAL::HI_CDG(12,1)
      REAL::HI_CEC(12,1)
      REAL::HI_CFNP(1)
      REAL::HI_CGCO2(31,1)
      REAL::HI_CGN2O(31,1)
      REAL::HI_CGO2(31,1)
      REAL::HI_CHL(1)
      REAL::HI_CHN(1)
      REAL::HI_CHS(1)
      REAL::HI_CHXA(1)
      REAL::HI_CHXP(1)
      REAL::HI_CKY(200)
      REAL::HI_CLA(12,1)
      REAL::HI_CLCO2(31,1)
      REAL::HI_CLG(1)
      REAL::HI_CLN2O(31,1)
      REAL::HI_CLO2(31,1)
      REAL::HI_CN0(1)
      REAL::HI_CN2(1)
      REAL::HI_CND(45,300,1)
      REAL::HI_CNDS(12,1)
      REAL::HI_CNLV(200)
      REAL::HI_CNRT(12,1)
      REAL::HI_CNSC(2,1)
      REAL::HI_CNSX(1)
      REAL::HI_CNY(200)
      REAL::HI_COOP(300)
      REAL::HI_COST(1)
      REAL::HI_COTL(300)
      REAL::HI_COWW(1)
      REAL::HI_CPFH(12,4)
      REAL::HI_CPHT(200,1)
      REAL::HI_CPMX(1)
      REAL::HI_CPRH(12,1)
      REAL::HI_CPRV(12,1)
      REAL::HI_CPVH(4)
      REAL::HI_CPY(200)
      REAL::HI_CST1(1)
      REAL::HI_CSTF(200,1)
      REAL::HI_CSTS(200)
      REAL::HI_CTSA(100,1)
      REAL::HI_CV(1)
      REAL::HI_CVF(1)
      REAL::HI_CVP(1)
      REAL::HI_CVRS(1)
      REAL::HI_CX(12,1)
      REAL::HI_CYAV(1)
      REAL::HI_CYMX(1)
      REAL::HI_CYSD(1)
      REAL::HI_DALG(1)
      REAL::HI_DCO2GEN(31,1)
      REAL::HI_DDLG(1)
      REAL::HI_DDM(200)
      REAL::HI_DEPC(1)
      REAL::HI_DHN(12,1)
      REAL::HI_DHT(1)
      REAL::HI_DKH(300)
      REAL::HI_DKHL(1)
      REAL::HI_DKI(300)
      REAL::HI_DKIN(1)
      REAL::HI_DLAI(200)
      REAL::HI_DLAP(2,200)
      REAL::HI_DM(200,1)
      REAL::HI_DM1(200,1)
      REAL::HI_DMF(200,1)
      REAL::HI_DMLA(200)
      REAL::HI_DMLX(200)
      REAL::HI_DN2G(31,1)
      REAL::HI_DN2OG(31,1)
      REAL::HI_DO2CONS(31,1)
      REAL::HI_DPMT(4)
      REAL::HI_DPRC(31,1)
      REAL::HI_DPRN(31,1)
      REAL::HI_DPRO(31,1)
      REAL::HI_DRAV(4)
      REAL::HI_DRT(1)
      REAL::HI_DRWX(31,1)
      REAL::HI_DST0(1)
      REAL::HI_DUMP(10,1)
      REAL::HI_DWOC(1)
      REAL::HI_EAR(31,1)
      REAL::HI_ECND(12,1)
      REAL::HI_EFI(1)
      REAL::HI_EFM(300)
      REAL::HI_EK(1)
      REAL::HI_EM10(1)
      REAL::HI_EMX(300)
      REAL::HI_EO5(30,1)
      REAL::HI_EP(200)
      REAL::HI_EQKE(12,1)
      REAL::HI_EQKS(12,1)
      REAL::HI_ERAV(4)
      REAL::HI_ETG(200,1)
      REAL::HI_EVRS(1)
      REAL::HI_EVRT(1)
      REAL::HI_EXCK(12,1)
      REAL::HI_EXTC(200)
      REAL::HI_FBM(1)
      REAL::HI_FC(31,1)
      REAL::HI_FCMN(1)
      REAL::HI_FCMP(1)
      REAL::HI_FCST(60)
      REAL::HI_FDSF(1)
      REAL::HI_FE26(12,1)
      REAL::HI_FFC(1)
      REAL::HI_FFED(10,1)
      REAL::HI_FFPQ(1)
      REAL::HI_FGC(1)
      REAL::HI_FGSL(1)
      REAL::HI_FHP(1)
      REAL::HI_FIRG(1)
      REAL::HI_FIRX(45,300,1)
      REAL::HI_FIXK(12,1)
      REAL::HI_FK(60)
      REAL::HI_FLT(200)
      REAL::HI_FN(60)
      REAL::HI_FNMA(60)
      REAL::HI_FNMN(60)
      REAL::HI_FNMX(45,1)
      REAL::HI_FNO(60)
      REAL::HI_FNP(5,1)
      REAL::HI_FOC(60)
      REAL::HI_FOP(12,1)
      REAL::HI_FP(60)
      REAL::HI_FPF(1)
      REAL::HI_FPO(60)
      REAL::HI_FPOP(300)
      REAL::HI_FPSC(1)
      REAL::HI_FRCP(300)
      REAL::HI_FRST(2,200)
      REAL::HI_FRTK(200,1)
      REAL::HI_FRTN(200,1)
      REAL::HI_FRTP(200,1)
      REAL::HI_FSFN(1)
      REAL::HI_FSFP(1)
      REAL::HI_FSLT(60)
      REAL::HI_FTO(200)
      REAL::HI_FULU(300)
      REAL::HI_GCOW(10,1)
      REAL::HI_GMA(1)
      REAL::HI_GMHU(200)
      REAL::HI_GRDD(200)
      REAL::HI_GRDL(1)
      REAL::HI_GRLV(200)
      REAL::HI_GSI(200)
      REAL::HI_GWMX(1)
      REAL::HI_GWPS(60,1)
      REAL::HI_GWSN(1)
      REAL::HI_GWST(1)
      REAL::HI_GZLM(10,1)
      REAL::HI_GZRT(10,1)
      REAL::HI_HA			!!Inserted MB 8/13/19; Changed 8/15/19
	  REAL::HI_HCL(12,1)
      REAL::HI_HCLD(1)
      REAL::HI_HCLN(1)
      REAL::HI_HE(300)
      REAL::HI_HI(200)
      REAL::HI_HKPC(31,1)
      REAL::HI_HKPN(31,1)
      REAL::HI_HKPO(31,1)
      REAL::HI_HLMN(1)
      REAL::HI_HMO(300)
      REAL::HI_HMX(200)
      REAL::HI_HR0(1)
      REAL::HI_HSM(1)
      REAL::HI_HU(200,1)
      REAL::HI_HUF(200,1)
      REAL::HI_HUI(200,1)
      REAL::HI_HUSC(45,300,1)
      REAL::HI_HYDV(4)
      REAL::HI_OCPD(1)
      REAL::HI_OMAP(1)
      REAL::HI_ORHI(300)
      REAL::HI_ORSD(1)
      REAL::HI_OSAA(1)
      REAL::HI_OWSA(1)
      REAL::HI_PAW(1)
      REAL::HI_PCOF(1)
      REAL::HI_PCST(60)
      REAL::HI_PCT(5,4)
      REAL::HI_PCTH(5,4)
      REAL::HI_PDAW(1)
      REAL::HI_PDPL(1)
      REAL::HI_PDPL0(1)
      REAL::HI_PDPLC(1)
      REAL::HI_PDPLX(1)
      REAL::HI_PDSKC(1)
      REAL::HI_PDSW(1)
      REAL::HI_PEC(1)
      REAL::HI_PFOL(60,1)
      REAL::HI_PH(12,1)
      REAL::HI_PHLF(60)
      REAL::HI_PHLS(60)
      REAL::HI_PHU(200,45,1)
      REAL::HI_PHUX(200)
      REAL::HI_PKOC(60)
      REAL::HI_PKRZ(12)
      REAL::HI_PLAX(200)
      REAL::HI_PLCH(60)
      REAL::HI_PM10(1)
      REAL::HI_PMX(1)
      REAL::HI_PO(12,1)
      REAL::HI_POP(200,45,1)
      REAL::HI_POPX(200)
      REAL::HI_PPCF(2,200)
      REAL::HI_PPL0(200,1)
      REAL::HI_PPLA(200,45,1)
      REAL::HI_PPLP(2,200)
      REAL::HI_PPX(13,1)
      REAL::HI_PQPS(5)
      REAL::HI_PRAV(4)
      REAL::HI_PRB(4)
      REAL::HI_PRSD(1)
      REAL::HI_PRYF(200)
      REAL::HI_PRYG(200)
      REAL::HI_PSO3(5)
      REAL::HI_PSOL(60)
      REAL::HI_PSON(5)
      REAL::HI_PSOP(5)
      REAL::HI_PSOQ(5)
      REAL::HI_PSOY(5)
      REAL::HI_PSP(12,1)
      REAL::HI_PSSF(60,12,1)
      REAL::HI_PSSP(5)
      REAL::HI_PST(200)
      REAL::HI_PSTE(45,60,1)
      REAL::HI_PSTF(1)
      REAL::HI_PSTM(1)
      REAL::HI_PSTR(45,60,1)
      REAL::HI_PSTS(1)
      REAL::HI_PSTZ(60,12,1)
      REAL::HI_PSZM(4)
      REAL::HI_PVQ(60,90,4)
      REAL::HI_PVY(60,90,4)
      REAL::HI_PWOF(60)
      REAL::HI_PYPS(5)
      REAL::HI_QC(4)
      REAL::HI_QCAP(1)
      REAL::HI_QDR(4)
      REAL::HI_QDRN(4)
      REAL::HI_QDRP(4)
      REAL::HI_QGA(720)
      REAL::HI_QHY(24,4,3)
      REAL::HI_QIN(12,1)
      REAL::HI_QIR(45,300,1)
      REAL::HI_QN(4)
      REAL::HI_QP(4)
      REAL::HI_QPR(4)
      REAL::HI_QPST(60,4)
      REAL::HI_QPU(4)
      REAL::HI_QRBQ(1)
      REAL::HI_QRF(4)
      REAL::HI_QRFN(4)
      REAL::HI_QRFP(4)
      REAL::HI_QRP(4)
      REAL::HI_QRQB(1)
      REAL::HI_QSF(12,4)
      REAL::HI_QURB(4)
      REAL::HI_QVOL(4)
      REAL::HI_RBMD(200)
      REAL::HI_RCBW(1)
      REAL::HI_RCF(1)
      REAL::HI_RCHC(1)
      REAL::HI_RCHD(1)
      REAL::HI_RCHK(1)
      REAL::HI_RCHL(1)
      REAL::HI_RCHN(1)
      REAL::HI_RCHS(1)
      REAL::HI_RCHX(1)
      REAL::HI_RCSS(1)
      REAL::HI_RCTC(4)
      REAL::HI_RCTW(1)
      REAL::HI_RD(200,1)
      REAL::HI_RDF(200,1)
      REAL::HI_RDMX(200)
      REAL::HI_REG(200,1)
      REAL::HI_REPI(1)
      REAL::HI_RF5(30,1)
      REAL::HI_RFDT(720)
      REAL::HI_RFPK(1)
      REAL::HI_RFPL(1)
      REAL::HI_RFPS(1)
      REAL::HI_RFPW(1)
      REAL::HI_RFPX(1)
      REAL::HI_RFTT(1)
      REAL::HI_RFV(1)
      REAL::HI_RFV0(1)
      REAL::HI_RHD(1)
      REAL::HI_RHT(300)
      REAL::HI_RHTT(1)
      REAL::HI_RIN(300)
      REAL::HI_RINT(1)
      REAL::HI_RLAD(200)
      REAL::HI_RLF(1)
      REAL::HI_RMXS(1)
      REAL::HI_RNMN(12,1)
      REAL::HI_ROK(12,1)
      REAL::HI_ROSP(1)
      REAL::HI_RQRB(4)
      REAL::HI_RR(300)
      REAL::HI_RRUF(1)
      REAL::HI_RSAE(1)
      REAL::HI_RSAP(1)
      REAL::HI_RSBD(1)
      REAL::HI_RSD(12,1)
      REAL::HI_RSDM(12,1)
      REAL::HI_RSDP(1)
      REAL::HI_RSEE(1)
      REAL::HI_RSEP(1)
      REAL::HI_RSF(1)
      REAL::HI_RSFN(4)
      REAL::HI_RSHC(1)
      REAL::HI_RSK(1)
      REAL::HI_RSLK(1)
      REAL::HI_RSO3(1)
      REAL::HI_RSOC(1)
      REAL::HI_RSON(1)
      REAL::HI_RSOP(1)
      REAL::HI_RSPC(31,1)
      REAL::HI_RSPK(1)
      REAL::HI_RSPS(60,4)
      REAL::HI_RSRR(1)
      REAL::HI_RSSA(1)
      REAL::HI_RSSF(4)
      REAL::HI_RSSP(1)
      REAL::HI_RST0(1)
      REAL::HI_RSTK(45,300,1)
      REAL::HI_RSV(1)
      REAL::HI_RSVB(1)
      REAL::HI_RSVE(1)
      REAL::HI_RSVF(1)
      REAL::HI_RSVP(1)
      REAL::HI_RSYB(1)
      REAL::HI_RSYF(1)
      REAL::HI_RSYN(1)
      REAL::HI_RSYS(1)
      REAL::HI_RVE0(1)
      REAL::HI_RVP0(1)
      REAL::HI_RW(200,1)
      REAL::HI_RWPC(2,200)
      REAL::HI_RWSA(4)
      REAL::HI_RWT(12,200,1)
      REAL::HI_RWTZ(31,1)
      REAL::HI_RZ(1)
      REAL::HI_RZSW(1)
      REAL::HI_S15(31,1)
      REAL::HI_S3(1)
      REAL::HI_SALA(1)
      REAL::HI_SALB(1)
      REAL::HI_SAMA(1)
      REAL::HI_SAN(12,1)
      REAL::HI_SATC(12,1)
      REAL::HI_SATK(1)
      REAL::HI_SCFS(30,1)
      REAL::HI_SCI(1)
      REAL::HI_SCNX(1)
      REAL::HI_SDVR(1)
      REAL::HI_SDW(200)
      REAL::HI_SET(12,1)
      REAL::HI_SEV(12,1)
      REAL::HI_SFCP(7,200,1)
      REAL::HI_SFMO(7,200,1)
      REAL::HI_SHYD(4)
      REAL::HI_SIL(12,1)
      REAL::HI_SLA0(200,1)
      REAL::HI_SLAI(200,1)
      REAL::HI_SLF(1)
      REAL::HI_SLT0(1)
      REAL::HI_SLTX(1)
      REAL::HI_SM(155,1)
      REAL::HI_SMAP(13,60,4)
      REAL::HI_SMAS(1)
      REAL::HI_SMB(12,1)
      REAL::HI_SMEA(31,1)
      REAL::HI_SMEO(1)
      REAL::HI_SMES(31,1)
      REAL::HI_SMFN(1)
      REAL::HI_SMFU(1)
      REAL::HI_SMH(35,4)
      REAL::HI_SMIO(4)
      REAL::HI_SMKS(1)
      REAL::HI_SMLA(1)
      REAL::HI_SMM(155,12,1)
      REAL::HI_SMMC(17,200,12,1)
      REAL::HI_SMMH(35,12,4)
      REAL::HI_SMMP(20,60,13,4)
      REAL::HI_SMMRP(5,60,12)
      REAL::HI_SMMU(1)
      REAL::HI_SMNS(1)
      REAL::HI_SMNU(1)
      REAL::HI_SMPL(1)
      REAL::HI_SMPQ(1)
      REAL::HI_SMPS(1)
      REAL::HI_SMPY(1)
      REAL::HI_SMRF(1)
      REAL::HI_SMRP(5,60,12)
      REAL::HI_SMS(11,13,1)
      REAL::HI_SMSS(1)
      REAL::HI_SMST(1)
      REAL::HI_SMTS(1)
      REAL::HI_SMWS(1)
      REAL::HI_SMX(1)
      REAL::HI_SMY(155,1)
      REAL::HI_SMY1(1)
      REAL::HI_SMY2(1)
      REAL::HI_SMYH(35,4)
      REAL::HI_SMYP(13,60,4)
      REAL::HI_SMYRP(5,60)
      REAL::HI_SNO(1)
      REAL::HI_SOIL(17,12,1)
      REAL::HI_SOL(23,12,1)
      REAL::HI_SOLK(31,1)
      REAL::HI_SOLQ(1)
      REAL::HI_SOT(31,1)
      REAL::HI_SPLG(1)
      REAL::HI_SQB(5,4)
      REAL::HI_SQVL(4)
      REAL::HI_SRA(200,1)
      REAL::HI_SRAD(1)
      REAL::HI_SRCH(27,4)
      REAL::HI_SRD(12,1)
      REAL::HI_SRMX(12,1)
      REAL::HI_SRSD(1)
      REAL::HI_SSF(12,4)
      REAL::HI_SSFCO2(31,1)
      REAL::HI_SSFI(1)
      REAL::HI_SSFN2O(31,1)
      REAL::HI_SSFO2(31,1)
      REAL::HI_SSIN(1)
      REAL::HI_SSPS(60)
      REAL::HI_SST(4)
      REAL::HI_SSW(1)
      REAL::HI_ST0(1)
      REAL::HI_STD(200,1)
      REAL::HI_STDA(4,200,1)
      REAL::HI_STDK(200,1)
      REAL::HI_STDL(200,1)
      REAL::HI_STDN(200,1)
      REAL::HI_STDO(1)
      REAL::HI_STDOK(1)
      REAL::HI_STDON(1)
      REAL::HI_STDOP(1)
      REAL::HI_STDP(200,1)
      REAL::HI_STFR(12,1)
      REAL::HI_STIR(300)
      REAL::HI_STKR(1)
      REAL::HI_STL(200,1)
      REAL::HI_STLT(1)
      REAL::HI_STMP(12,1)
      REAL::HI_STP(1)
      REAL::HI_STV(20,12,1)
      REAL::HI_STX(2,200)
      REAL::HI_STY(4)
      REAL::HI_SULF(12,1)
      REAL::HI_SUT(12,1)
      REAL::HI_SW(1)
      REAL::HI_SWB(1)
      REAL::HI_SWBD(1)
      REAL::HI_SWBX(1)
      REAL::HI_SWH(200,1)
      REAL::HI_SWLT(1)
      REAL::HI_SWP(200,1)
      REAL::HI_SWST(12,1)
      REAL::HI_SYB(5,4)
      REAL::HI_TAGP(1)
      REAL::HI_TAMX(12,1)
      REAL::HI_TBSC(200)
      REAL::HI_TC(4)
      REAL::HI_TCAV(4)
      REAL::HI_TCAW(200,1)
      REAL::HI_TCC(1)
      REAL::HI_TCMN(4)
      REAL::HI_TCMX(4)
      REAL::HI_TCN(12,1)
      REAL::HI_TCPA(200)
      REAL::HI_TCPY(200)
      REAL::HI_TCS(1)
      REAL::HI_TCVF(12,1)
      REAL::HI_TDM(200,1)
      REAL::HI_TEI(12,1)
      REAL::HI_TET(12,1)
      REAL::HI_TETG(200,1)
      REAL::HI_TFLG(1)
      REAL::HI_TFTK(200,1)
      REAL::HI_TFTN(200,1)
      REAL::HI_TFTP(200,1)
      REAL::HI_THK(1)
      REAL::HI_THRL(12,1)
      REAL::HI_THU(200,1)
      REAL::HI_TILG(1)
      REAL::HI_TIR(45,300,1)
      REAL::HI_TKR(1)
      REAL::HI_TLD(300)
      REAL::HI_TLMF(1)
      REAL::HI_TMN(1)
      REAL::HI_TMX(1)
      REAL::HI_TNOR(1)
      REAL::HI_TNYL(4)
      REAL::HI_TOC(1)
      REAL::HI_TOPC(200)
      REAL::HI_TPOR(31,1)
      REAL::HI_TPSF(1)
      REAL::HI_TQ(12,1)
      REAL::HI_TQN(12,1)
      REAL::HI_TQP(12,1)
      REAL::HI_TQPU(12,1)
      REAL::HI_TR(12,1)
      REAL::HI_TRA(200,1)
      REAL::HI_TRD(200,1)
      REAL::HI_TRHT(12,1)
      REAL::HI_TRSD(1)
      REAL::HI_TSFC(7,200,1)
      REAL::HI_TSFK(4)
      REAL::HI_TSFN(4)
      REAL::HI_TSLA(1)
      REAL::HI_TSMY(1)
      REAL::HI_TSN(12,1)
      REAL::HI_TSNO(1)
      REAL::HI_TSPS(60,4)
      REAL::HI_TSR(12,1)
      REAL::HI_TSY(12,1)
      REAL::HI_TVGF(1)
      REAL::HI_TVIR(200,1)
      REAL::HI_TXMN(12,1)
      REAL::HI_TXMX(12,1)
      REAL::HI_TYK(1)
      REAL::HI_TYL1(200,1)
      REAL::HI_TYL2(200,1)
      REAL::HI_TYLK(200,1)
      REAL::HI_TYLN(200,1)
      REAL::HI_TYLP(200,1)
      REAL::HI_TYN(1)
      REAL::HI_TYON(12,1)
      REAL::HI_TYP(1)
      REAL::HI_TYTP(12,1)
      REAL::HI_TYW(12,1)
      REAL::HI_U10(1)
      REAL::HI_UB1(1)
      REAL::HI_UK(12)
      REAL::HI_UK1(200,1)
      REAL::HI_UN(12)
      REAL::HI_UN1(200,1)
      REAL::HI_UNA(200,1)
      REAL::HI_UOB(1)
      REAL::HI_UP(12)
      REAL::HI_UP1(200,1)
      REAL::HI_UPSX(1)
      REAL::HI_URBF(1)
      REAL::HI_USL(1)
      REAL::HI_UW(12)
      REAL::HI_VAC(1)
      REAL::HI_VALF1(1)
      REAL::HI_VAP(1)
      REAL::HI_VAR(155,1)
      REAL::HI_VARC(17,200,1)
      REAL::HI_VARH(35,4)
      REAL::HI_VARP(12,60,4)
      REAL::HI_VARW(155)
      REAL::HI_VCHA(1)
      REAL::HI_VCHB(1)
      REAL::HI_VCO2(31,1)
      REAL::HI_VFC(31,1)
      REAL::HI_VFPA(1)
      REAL::HI_VFPB(1)
      REAL::HI_VIMX(1)
      REAL::HI_VIR(200,1)
      REAL::HI_VIRR(45,300,1)
      REAL::HI_VIRT(1)
      REAL::HI_VLG(1)
      REAL::HI_VLGB(1)
      REAL::HI_VLGI(1)
      REAL::HI_VLGM(1)
      REAL::HI_VLGN(1)
      REAL::HI_VN2O(31,1)
      REAL::HI_VNO3(12,1)
      REAL::HI_VO2(31,1)
      REAL::HI_VPD2(200)
      REAL::HI_VPTH(200)
      REAL::HI_VPU(1)
      REAL::HI_VQ(90,4)
      REAL::HI_VRSE(1)
      REAL::HI_VSK(1)
      REAL::HI_VSLT(1)
      REAL::HI_VURN(10,1)
      REAL::HI_VWC(31,1)
      REAL::HI_VWP(31,1)
      REAL::HI_VY(90,4)
      REAL::HI_WA(200)
      REAL::HI_WAC2(2,200)
      REAL::HI_WAVP(200)
      REAL::HI_WBMC(31,1)
      REAL::HI_WBMN(12,1)
      REAL::HI_WCHT(200,1)
      REAL::HI_WCMU(12,1)
      REAL::HI_WCO2G(31,1)
      REAL::HI_WCO2L(31,1)
      REAL::HI_WCOU(12,1)
      REAL::HI_WCY(200)
      REAL::HI_WDRM(1)
      REAL::HI_WFA(45,300,1)
      REAL::HI_WHPC(12,1)
      REAL::HI_WHPN(12,1)
      REAL::HI_WHSC(12,1)
      REAL::HI_WHSN(12,1)
      REAL::HI_WK(1)
      REAL::HI_WKMU(12,1)
      REAL::HI_WLM(12,1)
      REAL::HI_WLMC(12,1)
      REAL::HI_WLMN(12,1)
      REAL::HI_WLS(12,1)
      REAL::HI_WLSC(12,1)
      REAL::HI_WLSL(12,1)
      REAL::HI_WLSLC(12,1)
      REAL::HI_WLSLNC(12,1)
      REAL::HI_WLSN(12,1)
      REAL::HI_WLV(200,1)
      REAL::HI_WN2O(31,1)
      REAL::HI_WN2OG(31,1)
      REAL::HI_WN2OL(31,1)
      REAL::HI_WNH3(31,1)
      REAL::HI_WNMU(12,1)
      REAL::HI_WNO2(31,1)
      REAL::HI_WNO3(31,1)
      REAL::HI_WNOU(12,1)
      REAL::HI_WO2G(31,1)
      REAL::HI_WO2L(31,1)
      REAL::HI_WOC(12,1)
      REAL::HI_WON(12,1)
      REAL::HI_WPMA(12,1)
      REAL::HI_WPML(31,1)
      REAL::HI_WPMS(12,1)
      REAL::HI_WPMU(12,1)
      REAL::HI_WPO(12,1)
      REAL::HI_WPOU(12,1)
      REAL::HI_WS(1)
      REAL::HI_WSA(1)
      REAL::HI_WSLT(12,1)
      REAL::HI_WSX(1)
      REAL::HI_WSYF(200)
      REAL::HI_WT(12,1)
      REAL::HI_WTBL(1)
      REAL::HI_WTMB(1)
      REAL::HI_WTMN(1)
      REAL::HI_WTMU(1)
      REAL::HI_WTMX(1)
      REAL::HI_WXYF(200)
      REAL::HI_WYLD(4)
      REAL::HI_XCT(1)
      REAL::HI_XDLA0(200,1)
      REAL::HI_XDLAI(200)
      REAL::HI_XHSM(1)
      REAL::HI_XIDK(1)
      REAL::HI_XIDS(1)
      REAL::HI_XLAI(200,1)
      REAL::HI_XMAP(1)
      REAL::HI_XMS(30,1)
      REAL::HI_XMTU(200)
      REAL::HI_XN2O(31,1)
      REAL::HI_XNS(1)
      REAL::HI_XRFI(1)
      REAL::HI_XZP(13,13,1)
      REAL::HI_YC(4)
      REAL::HI_YCOU(4)
      REAL::HI_YCT(1)
      REAL::HI_YCWN(4)
      REAL::HI_YHY(720,4)
      REAL::HI_YLC(1)
      REAL::HI_YLD(200)
      REAL::HI_YLD1(200,1)
      REAL::HI_YLD2(200,1)
      REAL::HI_YLKF(200,1)
      REAL::HI_YLNF(200,1)
      REAL::HI_YLPF(200,1)
      REAL::HI_YLS(1)
      REAL::HI_YLX(200)
      REAL::HI_YMNU(4)
      REAL::HI_YN(4)
      REAL::HI_YNOU(4)
      REAL::HI_YNWN(4)
      REAL::HI_YP(4)
      REAL::HI_YPOU(4)
      REAL::HI_YPST(60,4)
      REAL::HI_YPWN(4)
      REAL::HI_YSD(8,4)
      REAL::HI_YTN(1)
      REAL::HI_YTX(1)
      REAL::HI_YW(4)
      REAL::HI_Z(12,1)
      REAL::HI_ZBMC(1)
      REAL::HI_ZBMN(1)
      REAL::HI_ZC(31,1)
      REAL::HI_ZCO(1)
      REAL::HI_ZCOB(1)
      REAL::HI_ZEK(1)
      REAL::HI_ZFK(1)
      REAL::HI_ZFOP(1)
      REAL::HI_ZHPC(1)
      REAL::HI_ZHPN(1)
      REAL::HI_ZHSC(1)
      REAL::HI_ZHSN(1)
      REAL::HI_ZLM(1)
      REAL::HI_ZLMC(1)
      REAL::HI_ZLMN(1)
      REAL::HI_ZLS(1)
      REAL::HI_ZLSC(1)
      REAL::HI_ZLSL(1)
      REAL::HI_ZLSLC(1)
      REAL::HI_ZLSLNC(1)
      REAL::HI_ZLSN(1)
      REAL::HI_ZNMA(1)
      REAL::HI_ZNMN(1)
      REAL::HI_ZNMU(1)
      REAL::HI_ZNOA(1)
      REAL::HI_ZNOS(1)
      REAL::HI_ZNOU(1)
      REAL::HI_ZOC(1)
      REAL::HI_ZON(1)
      REAL::HI_ZPMA(1)
      REAL::HI_ZPML(1)
      REAL::HI_ZPMS(1)
      REAL::HI_ZPMU(1)
      REAL::HI_ZPO(1)
      REAL::HI_ZPOU(1)
      REAL::HI_ZSK(1)
      REAL::HI_ZSLT(1)
      REAL::HI_ZTP(1)

      !!Missing
      !!added by IL for hisafe
      REAL::HI_HSG,HI_RTN1,HI_ZTK,HI_XLOG,HI_APM
      REAL::HI_BCHL,HI_BCHS
      REAL::HI_CHD,HI_UPN
      REAL::HI_SAT1,HI_FPS1,HI_CO2X,HI_CQNX,HI_RFNX
      REAL::HI_FMX,HI_SFLG
      REAL::HI_YWI,HI_BTA,HI_QG,HI_QCF,HI_CHS0,HI_BWD

      !!FI REPLACE II (# FOR FEEDING AREAS)
      INTEGER::HI_FI,HI_IWND,HI_IRFT,HI_ISOL,HI_IGMX,HI_IAZM,HI_IMO

      !!Missing
      !!added by IL for hisafe initialisation
      REAL::HI_NVCN0,HI_INFL0,HI_IMW0,HI_CO20,HI_CQN0,HI_FCW,HI_FPS0,HI_GWS0
      REAL::HI_RFT0,HI_RFP0,HI_SAT0,HI_FL0,HI_FW0,HI_ANG0,HI_DRV
      REAL::HI_DIAM,HI_GZL0,HI_RTN0,HI_PCO0,HI_RCC0,HI_RFN0

      END TYPE Hisafe_

      END MODULE HISAFE
