      SUBROUTINE NYON
!     APEX1501
!     THIS SUBPROGRAM PREDICTS DAILY ORGANIC N AND HUMUS LOSS, GIVEN
!     SOIL LOSS AND ENRICHMENT RATIO.
      USE PARM
      LD1=LID(1,ISA)
      TOT=WHPN(LD1,ISA)+WHSN(LD1,ISA)+WBMN(LD1,ISA)+WLMN(LD1,ISA)+WLSN&
      (LD1,ISA)
      YN(IDO)=YEW*TOT
      YNWN(IDO)=YEWN*TOT
      X1=MAX(1.E-5,1.-YEW-YEWN)
      WBMN(LD1,ISA)=WBMN(LD1,ISA)*X1
      WHSN(LD1,ISA)=WHSN(LD1,ISA)*X1
      WHPN(LD1,ISA)=WHPN(LD1,ISA)*X1
      WLSN(LD1,ISA)=WLSN(LD1,ISA)*X1
      WLMN(LD1,ISA)=MAX(.001,WLMN(LD1,ISA)*X1)
      X4=YMNU(IDO)*WNOU(LD1,ISA)/(RSDM(LD1,ISA)+1.E-10)
      !ZZ=WLMN(LD1,ISA)+WLSN(LD1,ISA)
      !IF(X4>ZZ)THEN
          !X4=ZZ
          !WLMN(LD1,ISA)=0.
          !WLSN(LD1,ISA)=0.
      !ELSE
          !RTO=MIN(1.,WLMN(LD1,ISA)/ZZ)
          !WLMN(LD1,ISA)=MAX(0.,WLMN(LD1,ISA)-RTO*X4)
          !WLSN(LD1,ISA)=WLSN(LD1,ISA)-X4*(1.-RTO)
      !END IF
      IF(WNOU(LD1,ISA)>=X4)THEN
          YNOU(IDO)=X4
      ELSE
          YNOU(IDO)=WNOU(LD1,ISA)
      END IF
      WNOU(LD1,ISA)=WNOU(LD1,ISA)-YNOU(IDO)
      RETURN
      END